---
:vkontakte:
  :accounts:
#  - :username: 'judywood@yandex.ru'
#    :password: '88omanon'
  - :username: 'Klim26'
    :password: 'P244w0rd'
  #- :username: qwerty317@mail.ru
  #  :password: 1qwerTy

  :apps:
  - :id: '2738601'
    :secret: 'frN0VGgc6iXa0I9Ls55X'
