---
:vkontakte:
  :accounts:
  - :username: 79232701050
    :password: suka666eba$na
  - :username: 79521395858
    :password: suka666eba$na
  - :username: 79673243738
    :password: suka666eba$na
  - :username: 79674710510
    :password: suka666eba$na
  - :username: 79817147761
    :password: suka666eba$na
  - :username: 79818062030
    :password: NiKooQMU5X
  - :username: 79818448602
    :password: 7Cd9NPLumE
  - :username: 79825717222
    :password: TQZAilDjZa
  - :username: 79823113750
    :password: 30BjPONjMm
  - :username: 79826182702
    :password: EgaMFlq3cl

  :apps:
  - :id: '2438996'
    :secret: 7SJMqnwodg0LxCoHLzud
