---
:vkontakte:
  :accounts:
  - :username: judywood@yandex.ru
    :password: 1qwerTyu
  - :username: qwerty317@mail.ru
    :password: 1qwerTy

  :apps:
  - :id: '2438996'
    :secret: 7SJMqnwodg0LxCoHLzud
