Parse_groups:
  cron: "39 * * * *"
  class: "::ParseGroups"
  queue: "bothunter"
  args: ""
  description: "parse groups"

Parse_groups:
  cron: "39 * * * *"
  class: "::ParseUsers"
  queue: "bh:profiles"
  args: ""
  description: "parse profiles"