Parse_groups:
  cron: "20 20 * * *"
  class: "::ParseGroups"
  queue: "bothunter"
  args: ""
  description: "parse groups"

Parse_groups:
  cron: "20 20 * * *"
  class: "::ParseUsers"
  queue: "bothunter"
  args: ""
  description: "parse profiles"